services:
  web:
    build: .
    container_name: my-flask-app
    command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:app
    volumes:
      - .:/app
    ports:
      - "8080:5000"
    env_file:
      - .env.prod
    environment:
      ENV_FILE: .env.prod
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: my-flask-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nome_do_banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: