"""Add is_google_user column to User

Revision ID: 39d54d836d62
Revises: b0cc26d4416f
Create Date: 2025-06-16 21:02:20.227189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d54d836d62'
down_revision = 'b0cc26d4416f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_google_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_google_user')

    # ### end Alembic commands ###
