"""Alterar tipo de hour para Time

Revision ID: 5359831e5c5c
Revises: f258e637e3a8
Create Date: 2025-05-28 22:36:20.657888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5359831e5c5c'
down_revision = 'f258e637e3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Time(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('hour',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
