"""Adicionado campo para contagem de registros de uso de medicamentos no models

Revision ID: 58fb88274ce8
Revises: 20d57413a935
Create Date: 2025-06-16 22:20:31.462386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fb88274ce8'
down_revision = '20d57413a935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cont_total_use_register', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_column('cont_total_use_register')

    # ### end Alembic commands ###
