"""Renomear campo password para password_hash e observaton para instructions

Revision ID: 8bdbe44be36f
Revises: 5359831e5c5c
Create Date: 2025-05-30 11:29:39.270905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bdbe44be36f'
down_revision = '5359831e5c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.drop_column('observation')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observation', sa.TEXT(), nullable=True))
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
