"""Adicionado campo frequência no model MedicationReminder

Revision ID: c1cb21bb1374
Revises: 3326def4131a
Create Date: 2025-06-11 21:50:02.285871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1cb21bb1374'
down_revision = '3326def4131a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicationsreminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicationsreminders', schema=None) as batch_op:
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###
